services:
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes:
    - mongo_db:/data/db

  api:
    build: .
    ports:
      - 8080:8080
    environment:
      PORT: 8080
      MONGODB_URI: mongodb://mongo_db:27017
      DB_NAME: my_db
      NAME: aditi
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}